name: 'Compile'

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  compile:
    runs-on: "ubuntu-latest"
    steps:
      - name: install dependencies
        uses: actions/checkout@v3

      - name: install dependencies
        run: sudo apt-get install liblimesuite-dev libliquid-dev libwebsockets-dev


      - name: Link check (warnings, changed files)
        run: |
          mkdir build;
          cd build;
          cmake ..;
          make;
          cd ..;
